
spring:
    application:
        name: cloudx-eureka

server:
    port: 32062

eureka:
    client:
        registerWithEureka: false  
        fetchRegistry: false      
        serviceUrl:
            defaultZone: http://127.0.0.1/eureka/

            
            
            